/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/cards": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cards.id"];
          created_at?: parameters["rowFilter.cards.created_at"];
          title?: parameters["rowFilter.cards.title"];
          subtitle?: parameters["rowFilter.cards.subtitle"];
          title_en?: parameters["rowFilter.cards.title_en"];
          image?: parameters["rowFilter.cards.image"];
          audio?: parameters["rowFilter.cards.audio"];
          cardset_id?: parameters["rowFilter.cards.cardset_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["cards"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** cards */
          cards?: definitions["cards"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cards.id"];
          created_at?: parameters["rowFilter.cards.created_at"];
          title?: parameters["rowFilter.cards.title"];
          subtitle?: parameters["rowFilter.cards.subtitle"];
          title_en?: parameters["rowFilter.cards.title_en"];
          image?: parameters["rowFilter.cards.image"];
          audio?: parameters["rowFilter.cards.audio"];
          cardset_id?: parameters["rowFilter.cards.cardset_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cards.id"];
          created_at?: parameters["rowFilter.cards.created_at"];
          title?: parameters["rowFilter.cards.title"];
          subtitle?: parameters["rowFilter.cards.subtitle"];
          title_en?: parameters["rowFilter.cards.title_en"];
          image?: parameters["rowFilter.cards.image"];
          audio?: parameters["rowFilter.cards.audio"];
          cardset_id?: parameters["rowFilter.cards.cardset_id"];
        };
        body: {
          /** cards */
          cards?: definitions["cards"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/cardsets": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cardsets.id"];
          created_at?: parameters["rowFilter.cardsets.created_at"];
          updated_at?: parameters["rowFilter.cardsets.updated_at"];
          title?: parameters["rowFilter.cardsets.title"];
          subtitle?: parameters["rowFilter.cardsets.subtitle"];
          image_url?: parameters["rowFilter.cardsets.image_url"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["cardsets"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** cardsets */
          cardsets?: definitions["cardsets"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cardsets.id"];
          created_at?: parameters["rowFilter.cardsets.created_at"];
          updated_at?: parameters["rowFilter.cardsets.updated_at"];
          title?: parameters["rowFilter.cardsets.title"];
          subtitle?: parameters["rowFilter.cardsets.subtitle"];
          image_url?: parameters["rowFilter.cardsets.image_url"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cardsets.id"];
          created_at?: parameters["rowFilter.cardsets.created_at"];
          updated_at?: parameters["rowFilter.cardsets.updated_at"];
          title?: parameters["rowFilter.cardsets.title"];
          subtitle?: parameters["rowFilter.cardsets.subtitle"];
          image_url?: parameters["rowFilter.cardsets.image_url"];
        };
        body: {
          /** cardsets */
          cardsets?: definitions["cardsets"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** flash cards */
  cards: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    created_at?: string;
    title?: string;
    subtitle?: string;
    title_en?: string;
    image?: string;
    audio?: string;
    /**
     * Note:
     * This is a Foreign Key to `cardsets.id`.<fk table='cardsets' column='id'/>
     */
    cardset_id?: number;
  };
  cardsets: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    created_at?: string;
    updated_at?: string;
    title?: string;
    subtitle?: string;
    image_url?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** cards */
  "body.cards": definitions["cards"];
  "rowFilter.cards.id": string;
  "rowFilter.cards.created_at": string;
  "rowFilter.cards.title": string;
  "rowFilter.cards.subtitle": string;
  "rowFilter.cards.title_en": string;
  "rowFilter.cards.image": string;
  "rowFilter.cards.audio": string;
  "rowFilter.cards.cardset_id": string;
  /** cardsets */
  "body.cardsets": definitions["cardsets"];
  "rowFilter.cardsets.id": string;
  "rowFilter.cardsets.created_at": string;
  "rowFilter.cardsets.updated_at": string;
  "rowFilter.cardsets.title": string;
  "rowFilter.cardsets.subtitle": string;
  "rowFilter.cardsets.image_url": string;
}

export interface operations {}

export interface external {}
